trigger:
- develop-ccc
- develop
- main

stages:
- stage: Unittest
  jobs:
  - job: unittest
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: Python Django Variables
      - name: lc.all
        value: 'en_US.UTF-8'
      - name: lang
        value: 'en_US.UTF-8'
      - name: tag
        value: '$(Build.BuildId)'

    strategy:
      matrix:
        Python38:
          PYTHON_VERSION: '3.8'
      maxParallel: 1

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(PYTHON_VERSION)'
        architecture: 'x64'
